FROM python:3.10-slim

# Install libGL for OpenCV to work
RUN apt-get update && apt-get install -y libgl1 && apt-get clean

# Set working directory
WORKDIR /app

# Copy requirements and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY . .

# Expose port if needed
EXPOSE 8000

# Command to run your app
CMD ["python", "app.py"]
